# Generated by Django 5.1.2 on 2024-11-06 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_historicalcar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadJsonCar',
        ),
    ]
